global:
  scrape_interval: 10s

scrape_configs:
- job_name: 'node'
  static_configs:
  - targets: ['service:9100'] # NOT localhost since we named the host of service in docker-compose file
- job_name: 'fastapi-app'
  static_configs:
    - targets: ['192.168.50.197:8000']